version: '3'

services:
  gpt-api:
    image: luchenyu/gpt-api
    runtime: nvidia
    shm_size: '80gb'
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - "1042:8000"
    command: ["--model", "deepseek-ai/DeepSeek-R1", "--trust-remote-code", "--max-model-len", "32768", "--tensor-parallel-size", "8", "--served-model-name", "DeepSeek-R1"]
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0,1,2,3,4,5,6,7" ]
              capabilities: [ gpu ]